### ISSUE TITLE
h3ToString segmentation fault

### ISSUE THREAD

**Issue by bakhritdinov** [neatlife/php-h3#3]
When I call the h3ToString function, returns the segmentation fault.

> $indexed = geoToH3(41.33032980000001, 69.31163190000008, 10);
> var_dump(h3ToString($indexed, 'h'));

**Comment by michaellindahl** [comment]
Also encountering this issue. My current workaround is calling geoToH3 directly:
```
exec('geoToH3 --resolution 10 --latitude 40.689167 --longitude -74.044444')
```

**Comment by michaellindahl** [comment]
Looks like this is happening with quite a few methods. These are the ones I'm noticing:
```
var_dump(h3ToParent($index, 5));
var_dump(h3ToChildren($index, 2));
var_dump(h3ToString($index, "hello world"));
var_dump(h3IndexesAreNeighbors($index, $index1));
var_dump(getH3UnidirectionalEdge($index, $index1));
var_dump(h3UnidirectionalEdgeIsValid($index));

var_dump(h3IndexesAreNeighbors($index, $index1));
var_dump(getH3UnidirectionalEdge($index, $index1));
var_dump(h3UnidirectionalEdgeIsValid($index));
var_dump(getOriginH3IndexFromUnidirectionalEdge($index));
var_dump(getDestinationH3IndexFromUnidirectionalEdge($index));
var_dump(getH3IndexesFromUnidirectionalEdge($index));
var_dump(getH3UnidirectionalEdgesFromHexagon($index));
var_dump(getH3UnidirectionalEdgeBoundary($index));
```

**Comment by michaellindahl** [comment]
This is a known issue from the latest [PR](https://github.com/neatlife/php-h3/pull/2), quotes translated by Google Translate:

> Thank you for submitting pr, ci test failed, there is segmentation fault, you can merge after solving this problem😄
> Merge first, then I will find a time to fix this segment fault😄

Although, looks like there's a fix possibly in the next [PR](https://github.com/neatlife/php-h3/pull/5):

> Fix bugs, add API, now support all APIs of current h3, modify the storage type of h3index
